[colors]
# 00 at the start means 100% transparent
background = #bf242424
# Slightly visible background for the active workspace (33 is ~20% opacity)
background-alt = #3382AAFF
foreground = #EEFFFF
primary = #82AAFF
secondary = #717CB4
alert = #FF5370
disabled = #444444

[bar/main]
# Multi-monitor support
monitor = ${env:MONITOR:}

width = 100%
height = 20pt
offset-x = 1%
offset-y = 8pt
radius = 0

# Transparent background
background = ${colors.background}
foreground = ${colors.foreground}

border-size = 0
line-size = 3pt

padding-left = 1
padding-right = 1
module-margin = 1

# Bold font helps readability against the wallpaper
font-0 = "JetBrainsMono Nerd Font:style=Bold:size=11;3"
font-1 = "JetBrainsMono Nerd Font:size=11;3"

modules-left = xworkspaces
modules-center = date
modules-right =  sep systray sep pulseaudio sep battery sep powermenu

cursor-click = pointer
enable-ipc = true

[module/sep]
type = custom/text
content = "|"
content-foreground = ${colors.disabled}

[module/xworkspaces]
type = internal/xworkspaces

label-active = %name%
label-active-background = ${colors.blue-gray}
label-active-foreground = ${colors.primary}
label-active-padding = 2
label-active-radius = 0  ; Adding rounded corners for pill shape
label-active-margin = 0  ; Margin ar0und the active label for spacing

label-occupied = %name%
label-occupied-padding = 2
label-occupied-radius = 0  ; Adding rounded corners for pill shape
label-occupied-margin = 0  ; Margin ar0und the occupied label for spacing

label-urgent = %name%
label-urgent-background = ${colors.alert}
label-urgent-padding = 0
label-urgent-radius = 0  ; Adding rounded corners for pill shape
label-urgent-margin = 0  ; Margin ar0und the urgent label for spacing

label-empty = %name%
label-empty-foreground = ${colors.disabled}
label-empty-padding = 0
label-empty-radius = 0  ; Adding rounded corners for pill shape
label-empty-margin = 0  ; Margin around the empty label for spacing

[module/xwindow]
type = internal/xwindow
label = %title:0:45:...%
label-foreground = ${colors.primary}

[module/systray]
type = internal/tray
format-margin = 2pt
tray-spacing = 10pt
tray-size = 14pt


[module/pulseaudio]
type = internal/pulseaudio

format-volume-prefix = " "
format-volume-prefix-foreground = ${colors.primary}
format-volume = <label-volume>

label-volume = %percentage%%

label-muted = " 0%" 
label-muted-foreground = ${colors.primary}

[module/battery]
type = internal/battery
full-at = 99
low-at = 15
battery = BAT0
adapter = AC
poll-interval = 5

# %{A1:...} means Left Click. It points to the script we just made.
format-charging = %{A1:~/.config/polybar/powerprofile.sh:}<label-charging>%{A}
format-discharging = %{A1:~/.config/polybar/powerprofile.sh:}<label-discharging>%{A}
format-full = %{A1:~/.config/polybar/powerprofile.sh:}<label-full>%{A}
format-low = %{A1:~/.config/polybar/powerprofile.sh:}<label-low>%{A}

label-charging = "󱐋 %percentage%%"
label-charging-foreground = ${colors.primary}
label-discharging = "󰁹 %percentage%%"
label-full = "󰁹 100%"
label-low = "󰂃 %percentage%%"
label-low-foreground = ${colors.alert}

[module/date]
type = internal/date
interval = 1
font=4
date = %I:%M %p  
date-alt = %d %B %Y %I:%M%p
label = %{F#ffffff% %{F-}%date%
label-foreground = ${colors.primary}

[module/powermenu]
type = custom/script
exec = echo "" $(whoami)
format-prefix = ""
format-prefix-foreground = ${colors.primary}
click-left = rofi -show power-menu -modi power-menu:rofi-power-menu
format-prefix-background = '#000'
